### ISSUE TITLE
W3ID löst nicht korrekt auf

### ISSUE THREAD

**Issue by ComeIn-NRW** [dini-ag-kim/schulformen#1]
http://w3id.org/kim/schulformen/ - Weiterleitung nicht intakt

**Comment by sroertgen** [comment]
guter Punkt. Ist hier auch noch gar nicht hinterlegt: https://github.com/perma-id/w3id.org/blob/master/kim/.htaccess

Kümmere ich mich drum

**Comment by sroertgen** [comment]
PR ist gestellt: https://github.com/perma-id/w3id.org/pull/2729

**Comment by sroertgen** [comment]
Funktioniert nun.
